wake:
	docker compose exec -it mock_microphone python3 microphone/play.py ok-nabu.wav

myname:
	docker compose exec -it mock_microphone python3 microphone/play.py whats-my-name.wav

yourname:
	docker compose exec -it mock_microphone python3 microphone/play.py whats-your-name.wav